language: objective-c
xcode_project: Producerify.xcodeproj
xcode_scheme: Producerify-OSX
osx_image: xcode7.2
before_install: true
install: true
git:
  submodules: false
script:
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.11/Carthage.pkg"
  - sudo installer -pkg "Carthage.pkg" -target /
  - rm "Carthage.pkg"
  - /usr/local/bin/carthage bootstrap --platform Mac
  - xctool -project Producerify.xcodeproj -scheme Producerify-OSX
